---

- hosts: all
  become: true
  tasks:

  - name: Update the repo Index
    apt: 
      update_cache: yes

  - name: Install Apache2 Package
    apt:
      name: apache2
      state: latest # each time the run the playbook, the packages are the latest version available
  - name: Add PHP support for Apache
    apt:
      name: libapache2-mod-php
